tr("Log in");
tr("Username:");
tr("Password:");
tr("My online status:");
tr("Remember");
tr("Login");
tr("Online");
tr("Busy");
tr("Be Right Back");
tr("Away");
tr("In a call");
tr("Out to Lunch");
tr("Show Offline");
